# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: split.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='split.proto',
  package='Lnkn_splitter',
  syntax='proto3',
  serialized_pb=_b('\n\x0bsplit.proto\x12\rLnkn_splitter\"\x1b\n\nData_chunk\x12\r\n\x05\x43hunk\x18\x01 \x01(\x0c\"9\n\x0b\x44\x61ta_header\x12\x17\n\x0f\x46inal_file_name\x18\x01 \x01(\t\x12\x11\n\tFile_name\x18\x02 \x03(\tb\x06proto3')
)




_DATA_CHUNK = _descriptor.Descriptor(
  name='Data_chunk',
  full_name='Lnkn_splitter.Data_chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Chunk', full_name='Lnkn_splitter.Data_chunk.Chunk', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=57,
)


_DATA_HEADER = _descriptor.Descriptor(
  name='Data_header',
  full_name='Lnkn_splitter.Data_header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Final_file_name', full_name='Lnkn_splitter.Data_header.Final_file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='File_name', full_name='Lnkn_splitter.Data_header.File_name', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['Data_chunk'] = _DATA_CHUNK
DESCRIPTOR.message_types_by_name['Data_header'] = _DATA_HEADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data_chunk = _reflection.GeneratedProtocolMessageType('Data_chunk', (_message.Message,), dict(
  DESCRIPTOR = _DATA_CHUNK,
  __module__ = 'split_pb2'
  # @@protoc_insertion_point(class_scope:Lnkn_splitter.Data_chunk)
  ))
_sym_db.RegisterMessage(Data_chunk)

Data_header = _reflection.GeneratedProtocolMessageType('Data_header', (_message.Message,), dict(
  DESCRIPTOR = _DATA_HEADER,
  __module__ = 'split_pb2'
  # @@protoc_insertion_point(class_scope:Lnkn_splitter.Data_header)
  ))
_sym_db.RegisterMessage(Data_header)


# @@protoc_insertion_point(module_scope)
